### Simple non-OO way

In [16]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -.8]]

weights = [[.2, .8, -.5, 1.0],
            [.5, -.91, .26, -.5],
            [-.26, -.27, .17, .87]]

biases = [2, 3, .5]

weights2 = [[.1, -.14, .5],
            [-.5, .12, -.33],
            [-.44, .73, -.13]]

biases2 = [-1, 2, -.5]

In [17]:
# Transpose weights, because np.dot expects dim 1 shape of matrix A
# to be equal to dim 0 shape of matrix B
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

### OO way

In [19]:
np.random.seed(0)

In [20]:
# Typically input data is capital X
X = [[1, 2, 3, 2.5],
     [2, 5, -1, 2],
     [-1.5, 2.7, 3.3, -.8]]

In [21]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # multiply by small value, so that rand vals are closer to 0
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons) # x by y matrix
        self.biases = np.zeros((1, n_neurons)) # takes shape as first param
    
    # forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [29]:
# shape of output needs to be same as next input, hence the fives
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

In [32]:
layer1.forward(X)
layer2.forward(layer1.output)

In [37]:
print(layer1.output, '\n')
print(layer2.output)

[[ 0.31835306  0.69519709  0.51953139 -0.04305516  0.56712282]
 [ 0.89654695  0.64941058  0.33951667 -0.91490653  0.86963754]
 [ 0.49708831  0.58571338 -0.19256797  0.25347126  0.1469059 ]] 

[[ 0.02151476  0.21264463]
 [ 0.25156569  0.20524615]
 [ 0.05955091 -0.04484078]]
