In [1]:
import numpy as np
import nnfs

nnfs.init()

We can say that Activation functions are functions that impart non-linearity to the network and is one of the factors that affect our results and accuracy of our model. 

### Rectified linear activation

In [10]:
X = [[1, 2, 3, 2.5],
     [2, 5, -1, 2],
     [-1.5, 2.7, 3.3, -.8]]

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []

# clips the inputs at 0
for i in inputs:
    if i > 0:
        output.append(i)
    elif i <= 0:
        output.append(0)

print(output)

# the same but better
print(np.maximum(0, inputs))

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]
[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [25]:
from nnfs.datasets import spiral_data

# 100 featuresets of 3 classes
X, y = spiral_data(100, 3)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        # multiply by small value, so that rand vals are closer to 0
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons) # x by y matrix
        self.biases = np.zeros((1, n_neurons)) # takes shape as first param
    
    # forward pass
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

layer1.forward(X)
activation1.forward(layer1.output)

print(activation1.output)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 2.8161443e-04 0.0000000e+00 7.4289892e-05 2.6191594e-03]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 2.0659240e-03]
 ...
 [1.8435162e-02 2.6441136e-02 0.0000000e+00 2.8828317e-02 4.5432087e-02]
 [1.6712803e-02 0.0000000e+00 1.7536987e-02 5.9250528e-03 0.0000000e+00]
 [1.8609155e-02 2.9045792e-02 0.0000000e+00 3.0489475e-02 6.0720660e-02]]
